//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusProviderApplication.BusProviderServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetProviderDetails_Result", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GetProviderDetails_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ProviderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganisationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProviderId {
            get {
                return this.ProviderIdField;
            }
            set {
                if ((this.ProviderIdField.Equals(value) != true)) {
                    this.ProviderIdField = value;
                    this.RaisePropertyChanged("ProviderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OrganisationName {
            get {
                return this.OrganisationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganisationNameField, value) != true)) {
                    this.OrganisationNameField = value;
                    this.RaisePropertyChanged("OrganisationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ContactNo {
            get {
                return this.ContactNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNoField, value) != true)) {
                    this.ContactNoField = value;
                    this.RaisePropertyChanged("ContactNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BusProviderServiceReference.ProvidersWebServiceSoap")]
    public interface ProvidersWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        BusProviderApplication.BusProviderServiceReference.HelloWorldResponse HelloWorld(BusProviderApplication.BusProviderServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<BusProviderApplication.BusProviderServiceReference.HelloWorldResponse> HelloWorldAsync(BusProviderApplication.BusProviderServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetProviderDetailsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProviderDetails", ReplyAction="*")]
        BusProviderApplication.BusProviderServiceReference.GetProviderDetailsResponse GetProviderDetails(BusProviderApplication.BusProviderServiceReference.GetProviderDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProviderDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<BusProviderApplication.BusProviderServiceReference.GetProviderDetailsResponse> GetProviderDetailsAsync(BusProviderApplication.BusProviderServiceReference.GetProviderDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertIntoProvider", ReplyAction="*")]
        BusProviderApplication.BusProviderServiceReference.InsertIntoProviderResponse InsertIntoProvider(BusProviderApplication.BusProviderServiceReference.InsertIntoProviderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertIntoProvider", ReplyAction="*")]
        System.Threading.Tasks.Task<BusProviderApplication.BusProviderServiceReference.InsertIntoProviderResponse> InsertIntoProviderAsync(BusProviderApplication.BusProviderServiceReference.InsertIntoProviderRequest request);
        
        // CODEGEN: Generating message contract since element name busName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertBusDetails", ReplyAction="*")]
        BusProviderApplication.BusProviderServiceReference.InsertBusDetailsResponse InsertBusDetails(BusProviderApplication.BusProviderServiceReference.InsertBusDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertBusDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<BusProviderApplication.BusProviderServiceReference.InsertBusDetailsResponse> InsertBusDetailsAsync(BusProviderApplication.BusProviderServiceReference.InsertBusDetailsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.BusProviderServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(BusProviderApplication.BusProviderServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.BusProviderServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(BusProviderApplication.BusProviderServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProviderDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProviderDetails", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.BusProviderServiceReference.GetProviderDetailsRequestBody Body;
        
        public GetProviderDetailsRequest() {
        }
        
        public GetProviderDetailsRequest(BusProviderApplication.BusProviderServiceReference.GetProviderDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetProviderDetailsRequestBody {
        
        public GetProviderDetailsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProviderDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProviderDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.BusProviderServiceReference.GetProviderDetailsResponseBody Body;
        
        public GetProviderDetailsResponse() {
        }
        
        public GetProviderDetailsResponse(BusProviderApplication.BusProviderServiceReference.GetProviderDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProviderDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BusProviderApplication.BusProviderServiceReference.GetProviderDetails_Result[] GetProviderDetailsResult;
        
        public GetProviderDetailsResponseBody() {
        }
        
        public GetProviderDetailsResponseBody(BusProviderApplication.BusProviderServiceReference.GetProviderDetails_Result[] GetProviderDetailsResult) {
            this.GetProviderDetailsResult = GetProviderDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertIntoProviderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertIntoProvider", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.BusProviderServiceReference.InsertIntoProviderRequestBody Body;
        
        public InsertIntoProviderRequest() {
        }
        
        public InsertIntoProviderRequest(BusProviderApplication.BusProviderServiceReference.InsertIntoProviderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertIntoProviderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contact;
        
        public InsertIntoProviderRequestBody() {
        }
        
        public InsertIntoProviderRequestBody(string name, string contact) {
            this.name = name;
            this.contact = contact;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertIntoProviderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertIntoProviderResponse", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.BusProviderServiceReference.InsertIntoProviderResponseBody Body;
        
        public InsertIntoProviderResponse() {
        }
        
        public InsertIntoProviderResponse(BusProviderApplication.BusProviderServiceReference.InsertIntoProviderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertIntoProviderResponseBody {
        
        public InsertIntoProviderResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertBusDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertBusDetails", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.BusProviderServiceReference.InsertBusDetailsRequestBody Body;
        
        public InsertBusDetailsRequest() {
        }
        
        public InsertBusDetailsRequest(BusProviderApplication.BusProviderServiceReference.InsertBusDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertBusDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string busName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int capacity;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int providerId;
        
        public InsertBusDetailsRequestBody() {
        }
        
        public InsertBusDetailsRequestBody(string busName, int capacity, string type, int providerId) {
            this.busName = busName;
            this.capacity = capacity;
            this.type = type;
            this.providerId = providerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertBusDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertBusDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.BusProviderServiceReference.InsertBusDetailsResponseBody Body;
        
        public InsertBusDetailsResponse() {
        }
        
        public InsertBusDetailsResponse(BusProviderApplication.BusProviderServiceReference.InsertBusDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertBusDetailsResponseBody {
        
        public InsertBusDetailsResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProvidersWebServiceSoapChannel : BusProviderApplication.BusProviderServiceReference.ProvidersWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProvidersWebServiceSoapClient : System.ServiceModel.ClientBase<BusProviderApplication.BusProviderServiceReference.ProvidersWebServiceSoap>, BusProviderApplication.BusProviderServiceReference.ProvidersWebServiceSoap {
        
        public ProvidersWebServiceSoapClient() {
        }
        
        public ProvidersWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProvidersWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProvidersWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProvidersWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusProviderApplication.BusProviderServiceReference.HelloWorldResponse BusProviderApplication.BusProviderServiceReference.ProvidersWebServiceSoap.HelloWorld(BusProviderApplication.BusProviderServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            BusProviderApplication.BusProviderServiceReference.HelloWorldRequest inValue = new BusProviderApplication.BusProviderServiceReference.HelloWorldRequest();
            inValue.Body = new BusProviderApplication.BusProviderServiceReference.HelloWorldRequestBody();
            BusProviderApplication.BusProviderServiceReference.HelloWorldResponse retVal = ((BusProviderApplication.BusProviderServiceReference.ProvidersWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusProviderApplication.BusProviderServiceReference.HelloWorldResponse> BusProviderApplication.BusProviderServiceReference.ProvidersWebServiceSoap.HelloWorldAsync(BusProviderApplication.BusProviderServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusProviderApplication.BusProviderServiceReference.HelloWorldResponse> HelloWorldAsync() {
            BusProviderApplication.BusProviderServiceReference.HelloWorldRequest inValue = new BusProviderApplication.BusProviderServiceReference.HelloWorldRequest();
            inValue.Body = new BusProviderApplication.BusProviderServiceReference.HelloWorldRequestBody();
            return ((BusProviderApplication.BusProviderServiceReference.ProvidersWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusProviderApplication.BusProviderServiceReference.GetProviderDetailsResponse BusProviderApplication.BusProviderServiceReference.ProvidersWebServiceSoap.GetProviderDetails(BusProviderApplication.BusProviderServiceReference.GetProviderDetailsRequest request) {
            return base.Channel.GetProviderDetails(request);
        }
        
        public BusProviderApplication.BusProviderServiceReference.GetProviderDetails_Result[] GetProviderDetails() {
            BusProviderApplication.BusProviderServiceReference.GetProviderDetailsRequest inValue = new BusProviderApplication.BusProviderServiceReference.GetProviderDetailsRequest();
            inValue.Body = new BusProviderApplication.BusProviderServiceReference.GetProviderDetailsRequestBody();
            BusProviderApplication.BusProviderServiceReference.GetProviderDetailsResponse retVal = ((BusProviderApplication.BusProviderServiceReference.ProvidersWebServiceSoap)(this)).GetProviderDetails(inValue);
            return retVal.Body.GetProviderDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusProviderApplication.BusProviderServiceReference.GetProviderDetailsResponse> BusProviderApplication.BusProviderServiceReference.ProvidersWebServiceSoap.GetProviderDetailsAsync(BusProviderApplication.BusProviderServiceReference.GetProviderDetailsRequest request) {
            return base.Channel.GetProviderDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusProviderApplication.BusProviderServiceReference.GetProviderDetailsResponse> GetProviderDetailsAsync() {
            BusProviderApplication.BusProviderServiceReference.GetProviderDetailsRequest inValue = new BusProviderApplication.BusProviderServiceReference.GetProviderDetailsRequest();
            inValue.Body = new BusProviderApplication.BusProviderServiceReference.GetProviderDetailsRequestBody();
            return ((BusProviderApplication.BusProviderServiceReference.ProvidersWebServiceSoap)(this)).GetProviderDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusProviderApplication.BusProviderServiceReference.InsertIntoProviderResponse BusProviderApplication.BusProviderServiceReference.ProvidersWebServiceSoap.InsertIntoProvider(BusProviderApplication.BusProviderServiceReference.InsertIntoProviderRequest request) {
            return base.Channel.InsertIntoProvider(request);
        }
        
        public void InsertIntoProvider(string name, string contact) {
            BusProviderApplication.BusProviderServiceReference.InsertIntoProviderRequest inValue = new BusProviderApplication.BusProviderServiceReference.InsertIntoProviderRequest();
            inValue.Body = new BusProviderApplication.BusProviderServiceReference.InsertIntoProviderRequestBody();
            inValue.Body.name = name;
            inValue.Body.contact = contact;
            BusProviderApplication.BusProviderServiceReference.InsertIntoProviderResponse retVal = ((BusProviderApplication.BusProviderServiceReference.ProvidersWebServiceSoap)(this)).InsertIntoProvider(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusProviderApplication.BusProviderServiceReference.InsertIntoProviderResponse> BusProviderApplication.BusProviderServiceReference.ProvidersWebServiceSoap.InsertIntoProviderAsync(BusProviderApplication.BusProviderServiceReference.InsertIntoProviderRequest request) {
            return base.Channel.InsertIntoProviderAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusProviderApplication.BusProviderServiceReference.InsertIntoProviderResponse> InsertIntoProviderAsync(string name, string contact) {
            BusProviderApplication.BusProviderServiceReference.InsertIntoProviderRequest inValue = new BusProviderApplication.BusProviderServiceReference.InsertIntoProviderRequest();
            inValue.Body = new BusProviderApplication.BusProviderServiceReference.InsertIntoProviderRequestBody();
            inValue.Body.name = name;
            inValue.Body.contact = contact;
            return ((BusProviderApplication.BusProviderServiceReference.ProvidersWebServiceSoap)(this)).InsertIntoProviderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusProviderApplication.BusProviderServiceReference.InsertBusDetailsResponse BusProviderApplication.BusProviderServiceReference.ProvidersWebServiceSoap.InsertBusDetails(BusProviderApplication.BusProviderServiceReference.InsertBusDetailsRequest request) {
            return base.Channel.InsertBusDetails(request);
        }
        
        public void InsertBusDetails(string busName, int capacity, string type, int providerId) {
            BusProviderApplication.BusProviderServiceReference.InsertBusDetailsRequest inValue = new BusProviderApplication.BusProviderServiceReference.InsertBusDetailsRequest();
            inValue.Body = new BusProviderApplication.BusProviderServiceReference.InsertBusDetailsRequestBody();
            inValue.Body.busName = busName;
            inValue.Body.capacity = capacity;
            inValue.Body.type = type;
            inValue.Body.providerId = providerId;
            BusProviderApplication.BusProviderServiceReference.InsertBusDetailsResponse retVal = ((BusProviderApplication.BusProviderServiceReference.ProvidersWebServiceSoap)(this)).InsertBusDetails(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusProviderApplication.BusProviderServiceReference.InsertBusDetailsResponse> BusProviderApplication.BusProviderServiceReference.ProvidersWebServiceSoap.InsertBusDetailsAsync(BusProviderApplication.BusProviderServiceReference.InsertBusDetailsRequest request) {
            return base.Channel.InsertBusDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusProviderApplication.BusProviderServiceReference.InsertBusDetailsResponse> InsertBusDetailsAsync(string busName, int capacity, string type, int providerId) {
            BusProviderApplication.BusProviderServiceReference.InsertBusDetailsRequest inValue = new BusProviderApplication.BusProviderServiceReference.InsertBusDetailsRequest();
            inValue.Body = new BusProviderApplication.BusProviderServiceReference.InsertBusDetailsRequestBody();
            inValue.Body.busName = busName;
            inValue.Body.capacity = capacity;
            inValue.Body.type = type;
            inValue.Body.providerId = providerId;
            return ((BusProviderApplication.BusProviderServiceReference.ProvidersWebServiceSoap)(this)).InsertBusDetailsAsync(inValue);
        }
    }
}
