//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusproviderWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackDetail
    {
        public int FeedbackId { get; set; }
        public int BusId { get; set; }
        public int TicketId { get; set; }
        public int Rating { get; set; }
    
        public virtual BusDetail BusDetail { get; set; }
        public virtual TicketDetail TicketDetail { get; set; }
    }
}
