//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusproviderWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RouteDetail()
        {
            this.TicketDetails = new HashSet<TicketDetail>();
        }
    
        public int RouteId { get; set; }
        public int BusId { get; set; }
        public int SourceId { get; set; }
        public int DestinationId { get; set; }
        public System.DateTime DateOfJourney { get; set; }
        public double Price { get; set; }
        public System.TimeSpan ArrivalTime { get; set; }
        public System.TimeSpan DepartureTime { get; set; }
    
        public virtual BusDetail BusDetail { get; set; }
        public virtual CityDetail CityDetail { get; set; }
        public virtual CityDetail CityDetail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketDetail> TicketDetails { get; set; }
    }
}
