//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusProviderApplication.ProviderServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetProviderDetails_Result", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GetProviderDetails_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ProviderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganisationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProviderId {
            get {
                return this.ProviderIdField;
            }
            set {
                if ((this.ProviderIdField.Equals(value) != true)) {
                    this.ProviderIdField = value;
                    this.RaisePropertyChanged("ProviderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OrganisationName {
            get {
                return this.OrganisationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganisationNameField, value) != true)) {
                    this.OrganisationNameField = value;
                    this.RaisePropertyChanged("OrganisationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ContactNo {
            get {
                return this.ContactNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNoField, value) != true)) {
                    this.ContactNoField = value;
                    this.RaisePropertyChanged("ContactNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProviderServiceReference.ProvidersWebServiceSoap")]
    public interface ProvidersWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        BusProviderApplication.ProviderServiceReference.HelloWorldResponse HelloWorld(BusProviderApplication.ProviderServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.HelloWorldResponse> HelloWorldAsync(BusProviderApplication.ProviderServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetProviderDetailsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProviderDetails", ReplyAction="*")]
        BusProviderApplication.ProviderServiceReference.GetProviderDetailsResponse GetProviderDetails(BusProviderApplication.ProviderServiceReference.GetProviderDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProviderDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.GetProviderDetailsResponse> GetProviderDetailsAsync(BusProviderApplication.ProviderServiceReference.GetProviderDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertIntoProvider", ReplyAction="*")]
        BusProviderApplication.ProviderServiceReference.InsertIntoProviderResponse InsertIntoProvider(BusProviderApplication.ProviderServiceReference.InsertIntoProviderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertIntoProvider", ReplyAction="*")]
        System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.InsertIntoProviderResponse> InsertIntoProviderAsync(BusProviderApplication.ProviderServiceReference.InsertIntoProviderRequest request);
        
        // CODEGEN: Generating message contract since element name busName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertBusDetails", ReplyAction="*")]
        BusProviderApplication.ProviderServiceReference.InsertBusDetailsResponse InsertBusDetails(BusProviderApplication.ProviderServiceReference.InsertBusDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertBusDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.InsertBusDetailsResponse> InsertBusDetailsAsync(BusProviderApplication.ProviderServiceReference.InsertBusDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name busNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteBus", ReplyAction="*")]
        BusProviderApplication.ProviderServiceReference.DeleteBusResponse DeleteBus(BusProviderApplication.ProviderServiceReference.DeleteBusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteBus", ReplyAction="*")]
        System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.DeleteBusResponse> DeleteBusAsync(BusProviderApplication.ProviderServiceReference.DeleteBusRequest request);
        
        // CODEGEN: Generating message contract since element name seatStatus from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BookSeat", ReplyAction="*")]
        BusProviderApplication.ProviderServiceReference.BookSeatResponse BookSeat(BusProviderApplication.ProviderServiceReference.BookSeatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BookSeat", ReplyAction="*")]
        System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.BookSeatResponse> BookSeatAsync(BusProviderApplication.ProviderServiceReference.BookSeatRequest request);
        
        // CODEGEN: Generating message contract since element name seatType from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeSeatType", ReplyAction="*")]
        BusProviderApplication.ProviderServiceReference.ChangeSeatTypeResponse ChangeSeatType(BusProviderApplication.ProviderServiceReference.ChangeSeatTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeSeatType", ReplyAction="*")]
        System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.ChangeSeatTypeResponse> ChangeSeatTypeAsync(BusProviderApplication.ProviderServiceReference.ChangeSeatTypeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.ProviderServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(BusProviderApplication.ProviderServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.ProviderServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(BusProviderApplication.ProviderServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProviderDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProviderDetails", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.ProviderServiceReference.GetProviderDetailsRequestBody Body;
        
        public GetProviderDetailsRequest() {
        }
        
        public GetProviderDetailsRequest(BusProviderApplication.ProviderServiceReference.GetProviderDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetProviderDetailsRequestBody {
        
        public GetProviderDetailsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProviderDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProviderDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.ProviderServiceReference.GetProviderDetailsResponseBody Body;
        
        public GetProviderDetailsResponse() {
        }
        
        public GetProviderDetailsResponse(BusProviderApplication.ProviderServiceReference.GetProviderDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProviderDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BusProviderApplication.ProviderServiceReference.GetProviderDetails_Result[] GetProviderDetailsResult;
        
        public GetProviderDetailsResponseBody() {
        }
        
        public GetProviderDetailsResponseBody(BusProviderApplication.ProviderServiceReference.GetProviderDetails_Result[] GetProviderDetailsResult) {
            this.GetProviderDetailsResult = GetProviderDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertIntoProviderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertIntoProvider", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.ProviderServiceReference.InsertIntoProviderRequestBody Body;
        
        public InsertIntoProviderRequest() {
        }
        
        public InsertIntoProviderRequest(BusProviderApplication.ProviderServiceReference.InsertIntoProviderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertIntoProviderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contact;
        
        public InsertIntoProviderRequestBody() {
        }
        
        public InsertIntoProviderRequestBody(string name, string contact) {
            this.name = name;
            this.contact = contact;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertIntoProviderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertIntoProviderResponse", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.ProviderServiceReference.InsertIntoProviderResponseBody Body;
        
        public InsertIntoProviderResponse() {
        }
        
        public InsertIntoProviderResponse(BusProviderApplication.ProviderServiceReference.InsertIntoProviderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertIntoProviderResponseBody {
        
        public InsertIntoProviderResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertBusDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertBusDetails", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.ProviderServiceReference.InsertBusDetailsRequestBody Body;
        
        public InsertBusDetailsRequest() {
        }
        
        public InsertBusDetailsRequest(BusProviderApplication.ProviderServiceReference.InsertBusDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertBusDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string busName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int capacity;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string busNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int providerId;
        
        public InsertBusDetailsRequestBody() {
        }
        
        public InsertBusDetailsRequestBody(string busName, int capacity, string type, string busNo, int providerId) {
            this.busName = busName;
            this.capacity = capacity;
            this.type = type;
            this.busNo = busNo;
            this.providerId = providerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertBusDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertBusDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.ProviderServiceReference.InsertBusDetailsResponseBody Body;
        
        public InsertBusDetailsResponse() {
        }
        
        public InsertBusDetailsResponse(BusProviderApplication.ProviderServiceReference.InsertBusDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertBusDetailsResponseBody {
        
        public InsertBusDetailsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteBusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteBus", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.ProviderServiceReference.DeleteBusRequestBody Body;
        
        public DeleteBusRequest() {
        }
        
        public DeleteBusRequest(BusProviderApplication.ProviderServiceReference.DeleteBusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteBusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string busNo;
        
        public DeleteBusRequestBody() {
        }
        
        public DeleteBusRequestBody(string busNo) {
            this.busNo = busNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteBusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteBusResponse", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.ProviderServiceReference.DeleteBusResponseBody Body;
        
        public DeleteBusResponse() {
        }
        
        public DeleteBusResponse(BusProviderApplication.ProviderServiceReference.DeleteBusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteBusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteBusResult;
        
        public DeleteBusResponseBody() {
        }
        
        public DeleteBusResponseBody(bool DeleteBusResult) {
            this.DeleteBusResult = DeleteBusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BookSeatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BookSeat", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.ProviderServiceReference.BookSeatRequestBody Body;
        
        public BookSeatRequest() {
        }
        
        public BookSeatRequest(BusProviderApplication.ProviderServiceReference.BookSeatRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BookSeatRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int seatNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int busId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string seatStatus;
        
        public BookSeatRequestBody() {
        }
        
        public BookSeatRequestBody(int seatNo, int busId, string seatStatus) {
            this.seatNo = seatNo;
            this.busId = busId;
            this.seatStatus = seatStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BookSeatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BookSeatResponse", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.ProviderServiceReference.BookSeatResponseBody Body;
        
        public BookSeatResponse() {
        }
        
        public BookSeatResponse(BusProviderApplication.ProviderServiceReference.BookSeatResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BookSeatResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool BookSeatResult;
        
        public BookSeatResponseBody() {
        }
        
        public BookSeatResponseBody(bool BookSeatResult) {
            this.BookSeatResult = BookSeatResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeSeatTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeSeatType", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.ProviderServiceReference.ChangeSeatTypeRequestBody Body;
        
        public ChangeSeatTypeRequest() {
        }
        
        public ChangeSeatTypeRequest(BusProviderApplication.ProviderServiceReference.ChangeSeatTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangeSeatTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int seatNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int busId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string seatType;
        
        public ChangeSeatTypeRequestBody() {
        }
        
        public ChangeSeatTypeRequestBody(int seatNo, int busId, string seatType) {
            this.seatNo = seatNo;
            this.busId = busId;
            this.seatType = seatType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeSeatTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeSeatTypeResponse", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.ProviderServiceReference.ChangeSeatTypeResponseBody Body;
        
        public ChangeSeatTypeResponse() {
        }
        
        public ChangeSeatTypeResponse(BusProviderApplication.ProviderServiceReference.ChangeSeatTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangeSeatTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ChangeSeatTypeResult;
        
        public ChangeSeatTypeResponseBody() {
        }
        
        public ChangeSeatTypeResponseBody(bool ChangeSeatTypeResult) {
            this.ChangeSeatTypeResult = ChangeSeatTypeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProvidersWebServiceSoapChannel : BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProvidersWebServiceSoapClient : System.ServiceModel.ClientBase<BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap>, BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap {
        
        public ProvidersWebServiceSoapClient() {
        }
        
        public ProvidersWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProvidersWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProvidersWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProvidersWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusProviderApplication.ProviderServiceReference.HelloWorldResponse BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap.HelloWorld(BusProviderApplication.ProviderServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            BusProviderApplication.ProviderServiceReference.HelloWorldRequest inValue = new BusProviderApplication.ProviderServiceReference.HelloWorldRequest();
            inValue.Body = new BusProviderApplication.ProviderServiceReference.HelloWorldRequestBody();
            BusProviderApplication.ProviderServiceReference.HelloWorldResponse retVal = ((BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.HelloWorldResponse> BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap.HelloWorldAsync(BusProviderApplication.ProviderServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.HelloWorldResponse> HelloWorldAsync() {
            BusProviderApplication.ProviderServiceReference.HelloWorldRequest inValue = new BusProviderApplication.ProviderServiceReference.HelloWorldRequest();
            inValue.Body = new BusProviderApplication.ProviderServiceReference.HelloWorldRequestBody();
            return ((BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusProviderApplication.ProviderServiceReference.GetProviderDetailsResponse BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap.GetProviderDetails(BusProviderApplication.ProviderServiceReference.GetProviderDetailsRequest request) {
            return base.Channel.GetProviderDetails(request);
        }
        
        public BusProviderApplication.ProviderServiceReference.GetProviderDetails_Result[] GetProviderDetails() {
            BusProviderApplication.ProviderServiceReference.GetProviderDetailsRequest inValue = new BusProviderApplication.ProviderServiceReference.GetProviderDetailsRequest();
            inValue.Body = new BusProviderApplication.ProviderServiceReference.GetProviderDetailsRequestBody();
            BusProviderApplication.ProviderServiceReference.GetProviderDetailsResponse retVal = ((BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap)(this)).GetProviderDetails(inValue);
            return retVal.Body.GetProviderDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.GetProviderDetailsResponse> BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap.GetProviderDetailsAsync(BusProviderApplication.ProviderServiceReference.GetProviderDetailsRequest request) {
            return base.Channel.GetProviderDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.GetProviderDetailsResponse> GetProviderDetailsAsync() {
            BusProviderApplication.ProviderServiceReference.GetProviderDetailsRequest inValue = new BusProviderApplication.ProviderServiceReference.GetProviderDetailsRequest();
            inValue.Body = new BusProviderApplication.ProviderServiceReference.GetProviderDetailsRequestBody();
            return ((BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap)(this)).GetProviderDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusProviderApplication.ProviderServiceReference.InsertIntoProviderResponse BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap.InsertIntoProvider(BusProviderApplication.ProviderServiceReference.InsertIntoProviderRequest request) {
            return base.Channel.InsertIntoProvider(request);
        }
        
        public void InsertIntoProvider(string name, string contact) {
            BusProviderApplication.ProviderServiceReference.InsertIntoProviderRequest inValue = new BusProviderApplication.ProviderServiceReference.InsertIntoProviderRequest();
            inValue.Body = new BusProviderApplication.ProviderServiceReference.InsertIntoProviderRequestBody();
            inValue.Body.name = name;
            inValue.Body.contact = contact;
            BusProviderApplication.ProviderServiceReference.InsertIntoProviderResponse retVal = ((BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap)(this)).InsertIntoProvider(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.InsertIntoProviderResponse> BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap.InsertIntoProviderAsync(BusProviderApplication.ProviderServiceReference.InsertIntoProviderRequest request) {
            return base.Channel.InsertIntoProviderAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.InsertIntoProviderResponse> InsertIntoProviderAsync(string name, string contact) {
            BusProviderApplication.ProviderServiceReference.InsertIntoProviderRequest inValue = new BusProviderApplication.ProviderServiceReference.InsertIntoProviderRequest();
            inValue.Body = new BusProviderApplication.ProviderServiceReference.InsertIntoProviderRequestBody();
            inValue.Body.name = name;
            inValue.Body.contact = contact;
            return ((BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap)(this)).InsertIntoProviderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusProviderApplication.ProviderServiceReference.InsertBusDetailsResponse BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap.InsertBusDetails(BusProviderApplication.ProviderServiceReference.InsertBusDetailsRequest request) {
            return base.Channel.InsertBusDetails(request);
        }
        
        public void InsertBusDetails(string busName, int capacity, string type, string busNo, int providerId) {
            BusProviderApplication.ProviderServiceReference.InsertBusDetailsRequest inValue = new BusProviderApplication.ProviderServiceReference.InsertBusDetailsRequest();
            inValue.Body = new BusProviderApplication.ProviderServiceReference.InsertBusDetailsRequestBody();
            inValue.Body.busName = busName;
            inValue.Body.capacity = capacity;
            inValue.Body.type = type;
            inValue.Body.busNo = busNo;
            inValue.Body.providerId = providerId;
            BusProviderApplication.ProviderServiceReference.InsertBusDetailsResponse retVal = ((BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap)(this)).InsertBusDetails(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.InsertBusDetailsResponse> BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap.InsertBusDetailsAsync(BusProviderApplication.ProviderServiceReference.InsertBusDetailsRequest request) {
            return base.Channel.InsertBusDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.InsertBusDetailsResponse> InsertBusDetailsAsync(string busName, int capacity, string type, string busNo, int providerId) {
            BusProviderApplication.ProviderServiceReference.InsertBusDetailsRequest inValue = new BusProviderApplication.ProviderServiceReference.InsertBusDetailsRequest();
            inValue.Body = new BusProviderApplication.ProviderServiceReference.InsertBusDetailsRequestBody();
            inValue.Body.busName = busName;
            inValue.Body.capacity = capacity;
            inValue.Body.type = type;
            inValue.Body.busNo = busNo;
            inValue.Body.providerId = providerId;
            return ((BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap)(this)).InsertBusDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusProviderApplication.ProviderServiceReference.DeleteBusResponse BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap.DeleteBus(BusProviderApplication.ProviderServiceReference.DeleteBusRequest request) {
            return base.Channel.DeleteBus(request);
        }
        
        public bool DeleteBus(string busNo) {
            BusProviderApplication.ProviderServiceReference.DeleteBusRequest inValue = new BusProviderApplication.ProviderServiceReference.DeleteBusRequest();
            inValue.Body = new BusProviderApplication.ProviderServiceReference.DeleteBusRequestBody();
            inValue.Body.busNo = busNo;
            BusProviderApplication.ProviderServiceReference.DeleteBusResponse retVal = ((BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap)(this)).DeleteBus(inValue);
            return retVal.Body.DeleteBusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.DeleteBusResponse> BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap.DeleteBusAsync(BusProviderApplication.ProviderServiceReference.DeleteBusRequest request) {
            return base.Channel.DeleteBusAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.DeleteBusResponse> DeleteBusAsync(string busNo) {
            BusProviderApplication.ProviderServiceReference.DeleteBusRequest inValue = new BusProviderApplication.ProviderServiceReference.DeleteBusRequest();
            inValue.Body = new BusProviderApplication.ProviderServiceReference.DeleteBusRequestBody();
            inValue.Body.busNo = busNo;
            return ((BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap)(this)).DeleteBusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusProviderApplication.ProviderServiceReference.BookSeatResponse BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap.BookSeat(BusProviderApplication.ProviderServiceReference.BookSeatRequest request) {
            return base.Channel.BookSeat(request);
        }
        
        public bool BookSeat(int seatNo, int busId, string seatStatus) {
            BusProviderApplication.ProviderServiceReference.BookSeatRequest inValue = new BusProviderApplication.ProviderServiceReference.BookSeatRequest();
            inValue.Body = new BusProviderApplication.ProviderServiceReference.BookSeatRequestBody();
            inValue.Body.seatNo = seatNo;
            inValue.Body.busId = busId;
            inValue.Body.seatStatus = seatStatus;
            BusProviderApplication.ProviderServiceReference.BookSeatResponse retVal = ((BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap)(this)).BookSeat(inValue);
            return retVal.Body.BookSeatResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.BookSeatResponse> BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap.BookSeatAsync(BusProviderApplication.ProviderServiceReference.BookSeatRequest request) {
            return base.Channel.BookSeatAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.BookSeatResponse> BookSeatAsync(int seatNo, int busId, string seatStatus) {
            BusProviderApplication.ProviderServiceReference.BookSeatRequest inValue = new BusProviderApplication.ProviderServiceReference.BookSeatRequest();
            inValue.Body = new BusProviderApplication.ProviderServiceReference.BookSeatRequestBody();
            inValue.Body.seatNo = seatNo;
            inValue.Body.busId = busId;
            inValue.Body.seatStatus = seatStatus;
            return ((BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap)(this)).BookSeatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusProviderApplication.ProviderServiceReference.ChangeSeatTypeResponse BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap.ChangeSeatType(BusProviderApplication.ProviderServiceReference.ChangeSeatTypeRequest request) {
            return base.Channel.ChangeSeatType(request);
        }
        
        public bool ChangeSeatType(int seatNo, int busId, string seatType) {
            BusProviderApplication.ProviderServiceReference.ChangeSeatTypeRequest inValue = new BusProviderApplication.ProviderServiceReference.ChangeSeatTypeRequest();
            inValue.Body = new BusProviderApplication.ProviderServiceReference.ChangeSeatTypeRequestBody();
            inValue.Body.seatNo = seatNo;
            inValue.Body.busId = busId;
            inValue.Body.seatType = seatType;
            BusProviderApplication.ProviderServiceReference.ChangeSeatTypeResponse retVal = ((BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap)(this)).ChangeSeatType(inValue);
            return retVal.Body.ChangeSeatTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.ChangeSeatTypeResponse> BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap.ChangeSeatTypeAsync(BusProviderApplication.ProviderServiceReference.ChangeSeatTypeRequest request) {
            return base.Channel.ChangeSeatTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.ChangeSeatTypeResponse> ChangeSeatTypeAsync(int seatNo, int busId, string seatType) {
            BusProviderApplication.ProviderServiceReference.ChangeSeatTypeRequest inValue = new BusProviderApplication.ProviderServiceReference.ChangeSeatTypeRequest();
            inValue.Body = new BusProviderApplication.ProviderServiceReference.ChangeSeatTypeRequestBody();
            inValue.Body.seatNo = seatNo;
            inValue.Body.busId = busId;
            inValue.Body.seatType = seatType;
            return ((BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap)(this)).ChangeSeatTypeAsync(inValue);
        }
    }
}
